apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: our-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dr14-make/kube-workshop.git
    targetRevision: HEAD
    path: 002-Helm/my-test-app
  destination:
    server: https://kubernetes.default.svc
    namespace: our-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
