apiVersion: v1
kind: Pod
metadata:
  name: env-example-first
  namespace: my-awesome-namespace
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: env-example-first
      image: ghcr.io/knative/helloworld-go:latest
      env:
        - name: TARGET
          value: "World"
      ports:
        - name: http-web-svc
          containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: env-example-second
  namespace: default
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: env-example-second
      image: ghcr.io/knative/helloworld-go:latest
      env:
        - name: TARGET
          value: "Make"
      ports:
        - name: http-web-svc
          containerPort: 8080
