apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: my-awesome-namespace
spec:
  containers:
    - name: hello-world
      image: hello-world
      ports:
        - containerPort: 80
  #     resources:
  #       requests:
  #         memory: "64Mi"
  #         cpu: "250m"
  #       limits:
  #         memory: "128Mi"
  #         cpu: "500m"
  # restartPolicy: OnFailure
