apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: my-awesome-namespace
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - name: http-web-svc
          containerPort: 80
