apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  TARGET: Make
---
apiVersion: v1
kind: Pod
metadata:
  name: env-example-third
  namespace: default
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: env-example-third
      image: ghcr.io/knative/helloworld-go:latest
      envFrom:
        - secretRef:
            name: secret-sa-sample
      ports:
        - name: http-web-svc
          containerPort: 8080
